# Generated by Django 5.2.8 on 2025-11-29 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="updated_at",
        ),
    ]
