# Generated by Django 5.2.8 on 2025-11-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_remove_book_created_at_remove_book_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="posted_by",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
